# Generated by Django 4.2.7 on 2023-11-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='имя пользователя в телеграм'),
        ),
    ]
