# Generated by Django 4.2.7 on 2023-11-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='period',
            field=models.CharField(choices=[('1', 'Раз в день'), ('2', 'Раз в два дня'), ('3', 'Раз в три дня'), ('4', 'Раз в четыре дня'), ('5', 'Раз в пять дней'), ('6', 'Раз в шесть дней'), ('7', 'Раз в неделю')], default='1', max_length=1, verbose_name='периодичность'),
        ),
    ]
