# Generated by Django 4.2.7 on 2023-11-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='period',
            field=models.CharField(blank=True, choices=[('1', 'Раз в день'), ('2', 'Раз в два дня'), ('3', 'Раз в три дня'), ('4', 'Раз в четыре дня'), ('5', 'Раз в пять дней'), ('6', 'Раз в шесть дней'), ('7', 'Раз в неделю')], default='1', max_length=1, null=True, verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='место'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='время'),
        ),
    ]
