# Generated by Django 4.2.7 on 2023-11-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habit_period_alter_habit_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='period',
            field=models.CharField(blank=True, choices=[('1', 'Раз в день'), ('2', 'Раз в два дня'), ('3', 'Раз в три дня'), ('4', 'Раз в четыре дня'), ('5', 'Раз в пять дней'), ('6', 'Раз в шесть дней'), ('7', 'Раз в неделю')], max_length=1, null=True, verbose_name='периодичность'),
        ),
    ]
